### ISSUE TITLE
Provide tagged string template functions

### ISSUE THREAD

**Issue by VitorLuizC** [VitorLuizC/normalize-text#15]
Would be nice to provide tagged string template functions.

Something like:

```js
normalizeWhiteSpaces`
  Hi, ${student.name}!
  How are you doing?
`;
//=> "Hi, Vitor! How are you doing?"
```

Seems that wouldn't be hard to do with current normalize functions. But maybe they should be scoped in a different way.

Some implementation details in the gist below:
https://gist.github.com/VitorLuizC/f80a9b51c3a686e5b5e35259bbf263fa

**Comment by phuvinhbmt** [comment]
Hi @VitorLuizC, this doesn't seem to need any further implementations, just test cases added. Can you review please ? https://github.com/VitorLuizC/normalize-text/pull/21
